"""empty message

Revision ID: 5864d08f4552
Revises: c6c63993e8b5
Create Date: 2018-03-01 14:13:49.509444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5864d08f4552'
down_revision = 'c6c63993e8b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check_work', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_work', sa.Column('test', mysql.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
