"""inition migrate

Revision ID: ceecf15ab4c0
Revises: fdd9fadf21c9
Create Date: 2017-11-23 14:54:46.550388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceecf15ab4c0'
down_revision = 'fdd9fadf21c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_work_date'), 'check_work', ['date'], unique=False)
    op.add_column(u'user', sa.Column('user_department', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'user_department')
    op.drop_index(op.f('ix_check_work_date'), table_name='check_work')
    op.drop_table('check_work')
    # ### end Alembic commands ###
